<?php

// NÃO APAGAR, ARQUIVO ANTI-BUG DO DATATABLES DA TELA DE VENDAS
// NÃO APAGAR, ARQUIVO ANTI-BUG DO DATATABLES DA TELA DE VENDAS
// NÃO APAGAR, ARQUIVO ANTI-BUG DO DATATABLES DA TELA DE VENDAS
// NÃO APAGAR, ARQUIVO ANTI-BUG DO DATATABLES DA TELA DE VENDAS
// NÃO APAGAR, ARQUIVO ANTI-BUG DO DATATABLES DA TELA DE VENDAS

?>